#!/bin/sh
#
# solrcloud SolrCloud Server
#
# chkconfig: - 80 05
# description: Enable SolrCloud Server
#

### BEGIN INIT INFO
# Provides:          Zookeeper
# Default-Start:
# Default-Stop:
# Required-Start:    $network
# Required-Stop:     $network
# Description:       Zookeeper Server
# Short-Description: Enable Zookeeper Server
### END INIT INFO

case "$1" in
    start|start-foreground|stop|restart|status|upgrade|print-cmd)
	sh /opt/zookeeper/bin/bin/zkServer.sh $1
	RETVAL=$?
	;;
    *)
	echo "Usage: $0 {start|start-foreground|stop|restart|status|upgrade|print-cmd}" >&2
        RETVAL=1
esac

exit $RETVAL
